# Generated by Django 2.2.3 on 2019-07-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190719_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(blank=True, max_length=200, verbose_name='Описание анонса'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание мероприятия'),
        ),
    ]
