# Generated by Django 2.2.3 on 2019-07-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания мероприятия'),
        ),
    ]
