# Generated by Django 2.2.3 on 2019-07-31 10:07

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_event_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='', validators=[main.models.validate_name], verbose_name='Изображение', width_field='width'),
        ),
    ]
