# Generated by Django 2.2.3 on 2019-08-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20190731_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('common', 'Обучение для всех'), ('prof', 'Обучение для профессионалов'), ('personal', 'Программы личностного роста'), ('university', 'Базовое психологическое образование')], default='common', max_length=20, verbose_name='Тип'),
        ),
    ]
