# Generated by Django 2.2.4 on 2019-08-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0012_auto_20190804_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(blank=True, max_length=300, verbose_name='Описание анонса'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='alt',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Описание фото'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Описание мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
