# Generated by Django 2.2.4 on 2019-08-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0013_auto_20190807_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание анонса'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='Описание мероприятия'),
        ),
    ]
