# Generated by Django 2.2.3 on 2019-07-19 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('main', '0019_auto_20190719_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('content_min', models.TextField(blank=True, max_length=300, verbose_name='Миниверсия статьи')),
                ('release_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выпуска статьи')),
                ('author',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='main.Person',
                                   verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'articles',
                'ordering': ['release_date'],
            },
        ),
        migrations.CreateModel(
            name='ArticlePhotoReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, height_field='height', null=True, upload_to='',
                                            verbose_name='Изображение', width_field='width')),
                ('alt', models.TextField(blank=True, max_length=200, verbose_name='Описание фото')),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos',
                                              to='blog.Article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Фото для статьи',
                'verbose_name_plural': 'Фото для статьи',
                'db_table': 'photos',
            },
        ),
    ]
