# Generated by Django 2.2.3 on 2019-07-19 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlephotoreport',
            options={'verbose_name': 'Фото для статей', 'verbose_name_plural': 'Фото для статей'},
        ),
    ]
