# Generated by Django 2.2.3 on 2019-07-19 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_auto_20190719_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author',
                                    to='workers.Person', verbose_name='Автор'),
        ),
    ]
