# Generated by Django 2.2.3 on 2019-07-20 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190719_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_min',
            field=models.TextField(blank=True, help_text='Как статья отображается в свернутом виде. Максимум 200 символов.', max_length=300, verbose_name='Миниверсия статьи'),
        ),
        migrations.AlterField(
            model_name='articlephotoreport',
            name='article',
            field=models.ForeignKey(help_text='К какой статье относится картинка', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='blog.Article', verbose_name='Статья'),
        ),
    ]
