# Generated by Django 2.1 on 2019-03-06 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('photo', models.FilePathField(null=True, path='C:\\Users\\gonch\\PycharmProjects\\psycho\\main\\static\\images')),
                ('priority', models.IntegerField(default=2)),
            ],
            options={
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('content', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('main', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True)),
                ('content_min', models.TextField(blank=True, max_length=300)),
                ('release_date', models.DateField()),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['release_date'],
            },
        ),
        migrations.CreateModel(
            name='ArticlePhotoReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alt', models.CharField(blank=True, max_length=200)),
                ('photo', models.FilePathField(null=True, path='C:\\Users\\gonch\\PycharmProjects\\psycho\\main\\static\\images')),
                ('announcement', models.BooleanField(default=False)),
                ('article', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Article')),
            ],
            options={
                'db_table': 'photos',
            },
        ),
        migrations.CreateModel(
            name='HelpItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'help',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('info', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.FilePathField(null=True, path='C:\\Users\\gonch\\PycharmProjects\\psycho\\main\\static\\images')),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'people',
            },
        ),
        migrations.AddField(
            model_name='helpitem',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Person'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Person'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Article'),
        ),
    ]
