# Generated by Django 2.2.3 on 2019-07-17 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['event__date'], 'verbose_name': 'Анонс', 'verbose_name_plural': 'Анонсы'},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='article',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='date',
        ),
        migrations.AddField(
            model_name='announcement',
            name='event',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='main.Event', verbose_name='Мероприятие'),
            preserve_default=False,
        ),
    ]
