# Generated by Django 2.2.3 on 2019-07-17 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_auto_20190717_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Анонс', 'verbose_name_plural': 'Анонсы'},
        ),
    ]
