# Generated by Django 2.1 on 2019-03-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190306_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=50, verbose_name='Полное имя'),
        ),
    ]
