# Generated by Django 2.2.3 on 2019-07-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190717_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['event__start_date'], 'verbose_name': 'Анонс', 'verbose_name_plural': 'Анонсы'},
        ),
    ]
