# Generated by Django 2.2.3 on 2019-07-17 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_auto_20190717_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['main', 'event__start_date'], 'verbose_name': 'Анонс',
                     'verbose_name_plural': 'Анонсы'},
        ),
    ]
