# Generated by Django 2.1 on 2019-03-06 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190306_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='photo',
            field=models.FilePathField(null=True, path='C:\\Users\\gonch\\PycharmProjects\\psycho\\main\\static\\images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='priority',
            field=models.IntegerField(default=2, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.CharField(blank=True, max_length=200, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(verbose_name='Дата события'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Отображать вверху'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Person', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_min',
            field=models.TextField(blank=True, max_length=300, verbose_name='Миниверсия статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='article',
            name='release_date',
            field=models.DateField(verbose_name='Дата выпуска статьи'),
        ),
        migrations.AlterField(
            model_name='articlephotoreport',
            name='alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='articlephotoreport',
            name='announcement',
            field=models.BooleanField(default=False, verbose_name='Добавить в анонсы'),
        ),
        migrations.AlterField(
            model_name='articlephotoreport',
            name='article',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articlephotoreport',
            name='photo',
            field=models.FilePathField(null=True, path='C:\\Users\\gonch\\PycharmProjects\\psycho\\main\\static\\images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='helpitem',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='helpitem',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Person', verbose_name='Эксперт'),
        ),
        migrations.AlterField(
            model_name='helpitem',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
