# Generated by Django 2.2.3 on 2019-07-17 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_auto_20190717_0830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-priority'], 'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
    ]
