# Generated by Django 2.2.3 on 2019-07-18 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0007_auto_20190717_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
    ]
