# Generated by Django 2.1 on 2019-03-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190306_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='release_date',
            field=models.DateField(auto_now=True, verbose_name='Дата выпуска статьи'),
        ),
    ]
