# Generated by Django 2.1 on 2019-03-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190306_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['date'], 'verbose_name': 'Анонс', 'verbose_name_plural': 'Анонсы'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['release_date'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='articlephotoreport',
            options={'verbose_name': 'Фото для статьи', 'verbose_name_plural': 'Фото для статьи'},
        ),
        migrations.AlterModelOptions(
            name='helpitem',
            options={'verbose_name': 'Пункт помощи', 'verbose_name_plural': 'Пункты помощи'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Специалист', 'verbose_name_plural': 'Специалисты'},
        ),
    ]
