# Generated by Django 2.1.7 on 2019-06-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190307_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='photo',
            field=models.FilePathField(null=True, path='/home/gda2048/Desktop/PhychoBlog/main/static/images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='articlephotoreport',
            name='photo',
            field=models.FilePathField(null=True, path='/home/gda2048/Desktop/PhychoBlog/main/static/images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FilePathField(blank=True, null=True, path='/home/gda2048/Desktop/PhychoBlog/main/static/images', verbose_name='Фотография'),
        ),
    ]
