# Generated by Django 2.2.3 on 2019-07-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190718_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='event',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(height_field='height', null=True, upload_to='', verbose_name='Изображение', width_field='width'),
        ),
        migrations.AddField(
            model_name='event',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='alt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='person',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(height_field='height', null=True, upload_to='', verbose_name='Изображение', width_field='width'),
        ),
    ]
