# Generated by Django 2.1.7 on 2019-06-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190627_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='photo',
            field=models.ImageField(height_field=100, null=True, upload_to='article/', verbose_name='Изображение', width_field=100),
        ),
        migrations.AlterField(
            model_name='articlephotoreport',
            name='photo',
            field=models.ImageField(height_field=100, null=True, upload_to='article/', verbose_name='Изображение', width_field=100),
        ),
    ]
