# Generated by Django 2.2.3 on 2019-07-19 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0012_auto_20190719_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='photo',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='',
                                    verbose_name='Изображение', width_field='width'),
        ),
        migrations.AlterField(
            model_name='articlephotoreport',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Article',
                                    verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articlephotoreport',
            name='photo',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='',
                                    verbose_name='Изображение', width_field='width'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='',
                                    verbose_name='Изображение', width_field='width'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата начала мероприятия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='',
                                    verbose_name='Изображение', width_field='width'),
        ),
    ]
