# Generated by Django 2.1.7 on 2019-06-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190627_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='width',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='articlephotoreport',
            name='height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='articlephotoreport',
            name='width',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='photo',
            field=models.ImageField(height_field='height', null=True, upload_to='article/', verbose_name='Изображение', width_field='width'),
        ),
        migrations.AlterField(
            model_name='articlephotoreport',
            name='photo',
            field=models.ImageField(height_field='height', null=True, upload_to='article/', verbose_name='Изображение', width_field='width'),
        ),
    ]
