# Generated by Django 2.2.3 on 2019-07-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0013_auto_20190719_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='alt',
            field=models.TextField(blank=True, max_length=200, verbose_name='Описание фото'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='priority',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='articlephotoreport',
            name='alt',
            field=models.TextField(blank=True, max_length=200, verbose_name='Описание фото'),
        ),
        migrations.AlterField(
            model_name='event',
            name='alt',
            field=models.TextField(blank=True, max_length=200, verbose_name='Описание фото'),
        ),
        migrations.AlterField(
            model_name='person',
            name='alt',
            field=models.TextField(blank=True, max_length=200, verbose_name='Описание фото'),
        ),
    ]
