# Generated by Django 2.1.7 on 2019-06-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190627_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FilePathField(blank=True, null=True, path='/home/gda2048/Desktop/PhychoBlog/psycho/static/images', verbose_name='Фотография'),
        ),
    ]
