# Generated by Django 2.2.3 on 2019-07-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190719_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='priority',
            field=models.IntegerField(default=2, verbose_name='Приоритет'),
        ),
    ]
