# Generated by Django 2.2.3 on 2019-07-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0015_auto_20190719_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выпуска статьи'),
        ),
        migrations.AlterField(
            model_name='helpitem',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
    ]
