# Generated by Django 2.2.2 on 2019-07-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190628_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(blank=True, max_length=200, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='helpitem',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Описание'),
        ),
    ]
