# Generated by Django 2.2.2 on 2019-07-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlephotoreport',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlephotoreport',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
