# Generated by Django 2.2.2 on 2019-07-07 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190707_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='expert',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.Person', verbose_name='Эксперт'),
            preserve_default=False,
        ),
    ]
