# Generated by Django 2.2.3 on 2019-07-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190719_1139'),
        ('main', '0019_auto_20190719_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpitem',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='HelpItem',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
