# Generated by Django 2.2.3 on 2019-07-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_achievement_expert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('content', models.TextField(blank=True, max_length=200, null=True, verbose_name='Контент')),
                ('start_date', models.DateField(verbose_name='Дата начала мероприятия')),
                ('duration', models.CharField(blank=True, max_length=20, null=True, verbose_name='Длительность')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'db_table': 'events',
            },
        ),
    ]
