# Generated by Django 2.2.4 on 2019-08-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, max_length=300, verbose_name='Про автора'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
    ]
