# Generated by Django 2.2.4 on 2019-08-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0022_auto_20190806_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='about',
            field=models.TextField(max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.TextField(max_length=500, verbose_name='Про автора'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True,
                                      verbose_name='Цена'),
        ),
    ]
