# Generated by Django 2.2.4 on 2019-08-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190806_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='alt',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Описание фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
