# Generated by Django 2.2.4 on 2019-08-07 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20190807_0658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
