# Generated by Django 2.2.4 on 2019-08-07 07:32

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, height_field='height', null=True, upload_to='', validators=[main.models.validate_name], verbose_name='Изображение', width_field='width')),
                ('alt', models.TextField(blank=True, max_length=300, null=True, verbose_name='Описание фото')),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('binary_image', models.BinaryField(null=True)),
                ('ext', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('about', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('author', models.TextField(max_length=500, verbose_name='Про автора')),
                ('description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('contacts', models.TextField(blank=True, verbose_name='Другие контактные данные: ')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'products',
            },
        ),
    ]
