# Generated by Django 2.2.3 on 2019-07-19 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('photo', models.ImageField(blank=True, height_field='height', null=True, upload_to='',
                                            verbose_name='Изображение', width_field='width')),
                ('alt', models.TextField(blank=True, max_length=200, verbose_name='Описание фото')),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50, verbose_name='Полное имя')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Логин')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('email', models.EmailField(max_length=254)),
                ('info', models.TextField(blank=True, verbose_name='Основная информация')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
                'db_table': 'people',
            },
        ),
        migrations.CreateModel(
            name='HelpItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.Person',
                                             verbose_name='Эксперт')),
            ],
            options={
                'verbose_name': 'Пункт помощи',
                'verbose_name_plural': 'Пункты помощи',
                'db_table': 'help',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, height_field='height', null=True, upload_to='',
                                            verbose_name='Изображение', width_field='width')),
                ('alt', models.TextField(blank=True, max_length=200, verbose_name='Описание фото')),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(default=2, verbose_name='Приоритет')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workers.Person',
                                             verbose_name='Эксперт')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'db_table': 'achievements',
                'ordering': ['-priority'],
            },
        ),
    ]
