# Generated by Django 2.2.3 on 2019-07-21 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('workers', '0002_auto_20190720_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-user__is_superuser'], 'verbose_name': 'Специалист',
                     'verbose_name_plural': 'Специалисты'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements',
                                    to='workers.Person', verbose_name='Эксперт'),
        ),
        migrations.AlterField(
            model_name='helpitem',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_items',
                                    to='workers.Person', verbose_name='Эксперт'),
        ),
    ]
