# Generated by Django 2.2.3 on 2019-07-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('workers', '0006_auto_20190726_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='ext',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='ext',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
