# Generated by Django 2.2.3 on 2019-07-31 10:07

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_add_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='photo',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='', validators=[main.models.validate_name], verbose_name='Изображение', width_field='width'),
        ),
        migrations.AlterField(
            model_name='person',
            name='contacts',
            field=models.TextField(blank=True, verbose_name='Другие контактные данные: '),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='', validators=[main.models.validate_name], verbose_name='Изображение', width_field='width'),
        ),
    ]
