# Generated by Django 2.2.4 on 2019-08-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('workers', '0009_auto_20190731_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='alt',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Описание фото'),
        ),
        migrations.AlterField(
            model_name='person',
            name='alt',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Описание фото'),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='Уникальный логин. При входе в систему его нужно будет указывать. ',
                                   max_length=50, unique=True, verbose_name='Логин'),
        ),
    ]
